require "administrate/base_dashboard"

class DevelopmentDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    creator: Field::BelongsTo.with_options(class_name: "User"),
    place: Field::BelongsTo,
    edits: Field::HasMany,
    flags: Field::HasMany,
    # editors: Field::HasMany.with_options(class_name: "User"),
    team_memberships: Field::HasMany.with_options(class_name: "DevelopmentTeamMembership"),
    team_members: Field::HasMany.with_options(class_name: "Organization"),
    moderators: Field::HasMany.with_options(class_name: "User"),
    subscriptions: Field::HasMany,
    subscribers: Field::HasMany.with_options(class_name: "User"),
    id: Field::Number,
    creator_id: Field::Number,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
    rdv: Field::Boolean,
    asofright: Field::Boolean,
    ovr55: Field::Boolean,
    clusteros: Field::Boolean,
    phased: Field::Boolean,
    stalled: Field::Boolean,
    name: Field::String,
    status: Field::String,
    desc: Field::Text,
    project_url: Field::String,
    mapc_notes: Field::String,
    tagline: Field::String,
    address: Field::String,
    state: Field::String,
    zip_code: Field::String,
    height: Field::Number,
    stories: Field::Number,
    year_compl: Field::Number,
    prjarea: Field::Number,
    singfamhu: Field::Number,
    twnhsmmult: Field::Number,
    lgmultifam: Field::Number,
    tothu: Field::Number,
    gqpop: Field::Number,
    rptdemp: Field::Number,
    emploss: Field::Number,
    estemp: Field::Number,
    commsf: Field::Number,
    hotelrms: Field::Number,
    onsitepark: Field::Number,
    total_cost: Field::Number,
    team_membership_count: Field::Number,
    cancelled: Field::Boolean,
    private: Field::Boolean,
    fa_ret: Field::Number.with_options(decimals: 2),
    fa_ofcmd: Field::Number.with_options(decimals: 2),
    fa_indmf: Field::Number.with_options(decimals: 2),
    fa_whs: Field::Number.with_options(decimals: 2),
    fa_rnd: Field::Number.with_options(decimals: 2),
    fa_edinst: Field::Number.with_options(decimals: 2),
    fa_other: Field::Number.with_options(decimals: 2),
    fa_hotel: Field::Number.with_options(decimals: 2),
    other_rate: Field::Number.with_options(decimals: 2),
    affordable: Field::Number.with_options(decimals: 2),
    latitude: Field::String.with_options(searchable: false),
    longitude: Field::String.with_options(searchable: false),
    street_view_heading: Field::Number,
    street_view_pitch: Field::Number,
    street_view_latitude: Field::String.with_options(searchable: false),
    street_view_longitude: Field::String.with_options(searchable: false),
    parcel_id: Field::String,
    mixed_use: Field::Boolean,
    nearest_transit: Field::String,
    point: Field::String.with_options(searchable: false),
    walkscore: Field::String,
    programs: Field::String,
    forty_b: Field::Boolean,
    residential: Field::Boolean,
    commercial: Field::Boolean,
  }.freeze

  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = [
    :creator,
    :place,
    :edits,
    :flags,
  ].freeze

  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = [
    :creator,
    :place,
    :edits,
    :flags,
    # :editors,
    :team_memberships,
    :team_members,
    # :moderators,
    :subscriptions,
    :subscribers,
    :id,
    :creator_id,
    :created_at,
    :updated_at,
    :rdv,
    :asofright,
    :ovr55,
    :clusteros,
    :phased,
    :stalled,
    :name,
    :status,
    :desc,
    :project_url,
    :mapc_notes,
    :tagline,
    :address,
    :state,
    :zip_code,
    :height,
    :stories,
    :year_compl,
    :prjarea,
    :singfamhu,
    :twnhsmmult,
    :lgmultifam,
    :tothu,
    :gqpop,
    :rptdemp,
    :emploss,
    :estemp,
    :commsf,
    :hotelrms,
    :onsitepark,
    :total_cost,
    :team_membership_count,
    :cancelled,
    :private,
    :fa_ret,
    :fa_ofcmd,
    :fa_indmf,
    :fa_whs,
    :fa_rnd,
    :fa_edinst,
    :fa_other,
    :fa_hotel,
    :other_rate,
    :affordable,
    :latitude,
    :longitude,
    :street_view_heading,
    :street_view_pitch,
    :street_view_latitude,
    :street_view_longitude,
    :parcel_id,
    :mixed_use,
    :nearest_transit,
    :point,
    :walkscore,
    :programs,
    :forty_b,
    :residential,
    :commercial,
  ].freeze

  # FORM_ATTRIBUTES
  # an array of attributes that will be displayed
  # on the model's form (`new` and `edit`) pages.
  FORM_ATTRIBUTES = [
    :creator,
    :place,
    :edits,
    :flags,
    # :editors,
    :team_memberships,
    :team_members,
    # :moderators,
    :subscriptions,
    :subscribers,
    :creator_id,
    :rdv,
    :asofright,
    :ovr55,
    :clusteros,
    :phased,
    :stalled,
    :name,
    :status,
    :desc,
    :project_url,
    :mapc_notes,
    :tagline,
    :address,
    :state,
    :zip_code,
    :height,
    :stories,
    :year_compl,
    :prjarea,
    :singfamhu,
    :twnhsmmult,
    :lgmultifam,
    :tothu,
    :gqpop,
    :rptdemp,
    :emploss,
    :estemp,
    :commsf,
    :hotelrms,
    :onsitepark,
    :total_cost,
    :team_membership_count,
    :cancelled,
    :private,
    :fa_ret,
    :fa_ofcmd,
    :fa_indmf,
    :fa_whs,
    :fa_rnd,
    :fa_edinst,
    :fa_other,
    :fa_hotel,
    :other_rate,
    :affordable,
    :latitude,
    :longitude,
    :street_view_heading,
    :street_view_pitch,
    :street_view_latitude,
    :street_view_longitude,
    :parcel_id,
    :mixed_use,
    :nearest_transit,
    :point,
    :walkscore,
    :programs,
    :forty_b,
    :residential,
    :commercial,
  ].freeze

  # Overwrite this method to customize how developments are displayed
  # across all pages of the admin dashboard.
  #
  # def display_resource(development)
  #   "Development ##{development.id}"
  # end
end
